server:
  port: 8081
spring:
  application:
    name: comment
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # characterEncoding=UTF-8 处理中文乱码
    url: jdbc:mysql://127.0.0.1:3306/comment?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: toor
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce: # redis 客户端为 Lettuce
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.sean.comment.entity # 别名扫描包
logging:
  level:
    com.sean.comment: debug